ckpt_root: ckpt
cuda: True
num_workers: 8

dataset:
    name: S2d3dDepthDataset
    common_kwargs:
        root: data/stanford2D3D
        hw: (256, 512)
        dmax: 100.
    train_kwargs:
        scene_txt: data/stanford2D3D/small_train.txt
        rand_rotate: True
        rand_flip: True
        rand_gamma: True
    valid_kwargs:
        scene_txt: data/stanford2D3D/small_test.txt
        rand_rotate: False
        rand_flip: False
        rand_gamma: False

training:
    optim: SGD
    epoch: 60
    batch_size: 8
    save_every: 60
    optim_lr: 0.01
    weight_decay: 0.0005
    optim_poly_gamma: 0.9
    optim_betas: (0.9, 0.999)

model:
    file: lib.model.hohonet
    modelclass: HoHoNet
    kwargs:
        emb_dim: 256
        backbone_config:
            module: Resnet
            kwargs:
                backbone: resnet50
                input_height: 256
        decode_config:
            module: EfficientHeightReduction
        refine_config:
            module: TransEn
            kwargs:
                position_encode: 128
                num_layers: 1
        modalities_config:
            DepthEstimator:
                basis: dct
                n_components: 64
                loss: l1
                output_height: 256

